# Mandatory parameter that should be set to the registered application's 
# 'API Key' value.
api_key:        

# Mandatory parameter that should be set to the registered application's
# 'Secret Key' value.
secret_key:         

# File to store client credential token
tokens_file:        tokens

# Fully Qualified Domain Name. Mandatory parameter that points to the location
# of AT&T's API.
FQDN:               https://api.att.com

# setup http sessions to use a provided secret
session_secret: 'super secret session key'

# Set this to use a proxy on the server side
proxy:              

# Used to set links on production sample apps, can be ignored
github_link:        http://localhost/github
download_link:      http://localhost/download
