proxy:
api_key: adfasdf
secret_key: asd
FQDN: http://localhost:8888

short_code_check: asdf
short_code_received: asdfaof

listener_limit: 5

download_link:  http://localhost:4567/download
github_link:    http://localhost:4567/source
