proxy: 
api_key:         
secret_key:       
FQDN:           https://api.att.com
redirect_url:   http://localhost:9292/authorization

channel_file:   channel.json
notifications_file: notifications.json
sub_expires_in: 3600
session_secret: 'super secret session key'

download_link:  http://localhost:9292/download
github_link:    http://localhost:9292/source
